//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int Id { get; set; }
        public int IdProductArticleNumber { get; set; }
        public int IdProductName { get; set; }
        public int IdNameUnit { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductMaxDiscount { get; set; }
        public int IdProductManufacturer { get; set; }
        public int IdProductSupplier { get; set; }
        public int IdProductCategory { get; set; }
        public int ProductDiscount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        public byte[] PhotoImage { get; set; }
    
        public virtual NameManufacturer NameManufacturer { get; set; }
        public virtual NameSupplier NameSupplier { get; set; }
        public virtual NameUnit NameUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductName ProductName { get; set; }
    }
}
